version: "2"
plugins:
  eslint:
    enabled: false
checks:
  method-lines:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 50
  identical-code:
    config:
      threshold: 50
exclude_patterns:
  - "**/node_modules/"
  - "**/test/"
  - "**/UI/"
  - "**/.nyc_output"
  - "**/coverage"