sudo: false
language: node_js
node_js:
  - node
script:
  - npm run coverage
cache:
  directories:
    - node_modules
after_succes:
  - npm run coveralls
notifications:
  email:
    on_success: never
    on_failure: never